[versions]
groovy = "3.0.5"
checkstyle = "8.37"
jupiter = "5.9.2"
flyway = "8.1.0"

[libraries]
groovy-core = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
groovy-json = { module = "org.codehaus.groovy:groovy-json", version.ref = "groovy" }
groovy-nio = { module = "org.codehaus.groovy:groovy-nio", version.ref = "groovy" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version = { strictly = "[3.8, 4.0[", prefer="3.9" } }

flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway"}

# libraries for testing
junit-jupiter = { module="org.junit.jupiter:junit-jupiter-api", version.ref="jupiter" }
junit-engine = { module="org.junit.jupiter:junit-jupiter-engine" }

[bundles]
groovy = ["groovy-core", "groovy-json", "groovy-nio"]
testDependencies = ["junit-jupiter", "junit-engine"]